// Shared merge helpers for the LSP capability docs (#390). The nightly runs on
// ubuntu-latest, which lacks many language toolchains, so a naive overwrite would
// DROP rows a richer run (e.g. the dev box) captured. These helpers MERGE: a row
// the current run measured is updated in place; a row it didn't measure (server
// unavailable/unknown here) is preserved verbatim. Server-row count never
// shrinks. Used by characterize-lsp.mjs + probe-clean-signal.mjs (which share
// docs/lsp-capability-matrix.md) and server-capabilities.mjs. #460/#390.
//
// Deliberately dependency-free: tests and scripts copy this file alone into a
// scratch checkout (release-qa.test.ts), so it imports nothing.

/**
 * The generated LSP docs the nightly regenerates and `check-generated-docs-diff`
 * compares against HEAD. One list, so a doc added to the nightly cannot be
 * regenerated without being compared (#3645 added the idle-eviction document);
 * the refresh PR's `add-paths` in tool-smoke.yml must carry the same paths.
 */
export const GENERATED_LSP_DOCS = [
	"docs/lsp-capability-matrix.md",
	"docs/servercapabilities.md",
	"docs/lsp-idle-eviction.md",
];

/**
 * Parse a GitHub-flavoured Markdown table into { header, aligns, rows } where
 * rows is an array of cell-string arrays. Only the FIRST table after `afterLine`
 * (a line whose text includes the marker) is parsed. Returns null if not found.
 *
 * @param {string} text
 * @param {string} headerMarker  a substring of the table's header row (e.g. "| lang | server |")
 * @returns {{ start: number, end: number, header: string[], sep: string, rows: string[][] } | null}
 */
export function parseTable(text, headerMarker) {
	const lines = text.split("\n");
	let headerIdx = -1;
	for (let i = 0; i < lines.length; i++) {
		if (lines[i].includes(headerMarker) && lines[i].trim().startsWith("|")) {
			headerIdx = i;
			break;
		}
	}
	if (headerIdx < 0 || headerIdx + 1 >= lines.length) return null;
	const sepIdx = headerIdx + 1;
	if (!/^\s*\|?[\s:|-]+\|?\s*$/.test(lines[sepIdx])) return null;
	const header = splitRow(lines[headerIdx]);
	const rows = [];
	let end = sepIdx + 1;
	for (let i = sepIdx + 1; i < lines.length; i++) {
		if (!lines[i].trim().startsWith("|")) break;
		rows.push(splitRow(lines[i]));
		end = i + 1;
	}
	return { start: headerIdx, end, header, sep: lines[sepIdx], rows };
}

function splitRow(line) {
	// Strip leading/trailing pipe then split; trim each cell.
	const trimmed = line.trim().replace(/^\|/, "").replace(/\|$/, "");
	return trimmed.split("|").map((c) => c.trim());
}

function renderRow(cells) {
	return `| ${cells.join(" | ")} |`;
}

/**
 * Compare strings by Unicode code point, independently of the host locale.
 * Generated docs must not change when a runner's locale changes.
 */
export function compareStableStrings(a, b) {
	return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * Compare generated docs while ignoring the intentionally volatile date marker.
 * The marker remains in rendered output; only the no-op refresh decision omits
 * it so a date-only nightly cannot open a PR (#3380).
 */
export function compareGeneratedDocs(a, b) {
	const withoutGenerationDate = (text) =>
		text
			.split("\n")
			.filter((line) => !/^_Last generated: .*_$/.test(line))
			.join("\n");
	return (
		compareStableStrings(withoutGenerationDate(a), withoutGenerationDate(b)) !==
		0
	);
}

export function sortedStrings(values) {
	return [...(values ?? [])].map(String).sort(compareStableStrings);
}

/**
 * Render the server capability inventory without depending on handshake order.
 * The caller supplies the measured date/platform so this remains pure and easy
 * to test with two differently ordered inventories.
 */
/**
 * #3407: the save column. `none` renders as the table's "not advertised" dot;
 * a snapshot without the field (a client predating the accessor) is `?`, never
 * a dot, because "unknown" must not read as "declares no save".
 */
function saveCell(textDocumentSave) {
	if (textDocumentSave === "save" || textDocumentSave === "save+text")
		return textDocumentSave;
	if (textDocumentSave === "none") return "·";
	return "?";
}

export function renderServerCapabilitiesDoc({
	rows,
	unavailable,
	date,
	platform,
	ops,
}) {
	const sortedRows = [...rows].sort((a, b) =>
		compareStableStrings(String(a.serverId), String(b.serverId)),
	);
	const sortedOps = [...ops];
	const yn = (b) => (b ? "✓" : "·");
	const lines = [
		"# LSP server capability inventory",
		"",
		"Advertised capabilities of every LSP server pi-lens supports, read from each",
		"server's `initialize` handshake. Generated by `node scripts/server-capabilities.mjs",
		"[--install]` (requires `npm run build:dist`). Servers whose toolchain/binary is",
		"absent on the generating host are listed under *Unavailable* — run in a",
		"provisioned environment (the nightly) to capture those rows.",
		"",
		`_Last generated: ${date} on ${platform}; ${sortedRows.length} servers captured, ${unavailable.size} unavailable._`,
		"",
		"## Diagnostic mode + navigation/edit operations",
		"",
		`Legend: ✓ advertised, · not. **mode** = document diagnostics (\`pull\` = \`textDocument/diagnostic\`, else push-only); **ws-pull** = advertises \`workspace/diagnostic\` (one project-wide pull — the #387 Item 2 fast path); **save** = \`textDocumentSync.save\` (#3407): \`save\` gets \`textDocument/didSave\`, \`save+text\` gets it with the document text (\`includeText\`), · declares none, ? not captured. ${sortedOps.map(([k, a]) => `**${a}**=${k}`).join(", ")}; **cmds** = executeCommand allowlist size.`,
		"",
		`| server | mode | ws-pull | save | ${sortedOps.map(([, a]) => a).join(" | ")} | cmds |`,
		`|---|---|---|---|${sortedOps.map(() => "---").join("|")}|---|`,
	];
	for (const s of sortedRows) {
		const operationSupport = s.operationSupport ?? {};
		const opsText = sortedOps.map(([k]) => yn(operationSupport[k])).join(" | ");
		lines.push(
			`| ${s.serverId} | ${s.workspaceDiagnosticsSupport?.mode ?? "?"} | ${yn(s.workspaceDiagnosticsSupport?.workspaceDiagnostics)} | ${saveCell(s.textDocumentSave)} | ${opsText} | ${sortedStrings(s.advertisedCommands).length} |`,
		);
	}
	lines.push(
		"",
		"## Raw advertised capability keys",
		"",
		"Top-level keys of each server's `ServerCapabilities` — the full advertised",
		"surface, including providers pi-lens does not yet consume.",
		"",
	);
	for (const s of sortedRows) {
		const keys = sortedStrings(s.rawCapabilityKeys);
		lines.push(
			`- **${s.serverId}**: ${keys.length ? keys.join(", ") : "(none reported)"}`,
		);
	}
	const withCmds = sortedRows.filter(
		(s) => sortedStrings(s.advertisedCommands).length > 0,
	);
	if (withCmds.length) {
		lines.push("", "## Advertised executeCommand allowlists", "");
		for (const s of withCmds) {
			const commands = sortedStrings(s.advertisedCommands);
			const shown = commands.slice(0, 40).join(", ");
			const more = commands.length > 40 ? ", …" : "";
			lines.push(`- **${s.serverId}** (${commands.length}): ${shown}${more}`);
		}
	}
	const unavailableSorted = sortedStrings(unavailable);
	if (unavailableSorted.length) {
		lines.push(
			"",
			"## Unavailable on the generating host",
			"",
			"Toolchain/binary not installed here, so capabilities weren't captured",
			"(many are the toolchain-gated family tracked in #241):",
			"",
		);
		for (const name of unavailableSorted) lines.push(`- ${name}`);
	}
	lines.push("");
	return lines.join("\n");
}

/**
 * Merge measured rows into an existing table's rows, keyed by a column index.
 * For each measured row, only the columns named in `ownedCols` are overwritten
 * (so two scripts sharing a table each update only their own columns); unlisted
 * columns keep the existing value. Rows present in the doc but NOT measured this
 * run are preserved. New servers are appended.
 *
 * @param {string[][]} existing   parsed existing rows
 * @param {string[]} header       column headers (for name→index)
 * @param {Object[]} measured     objects keyed by header name → cell value
 * @param {string} keyCol         header name of the unique key (e.g. "lang")
 * @param {string[]} ownedCols    header names this run is authoritative for
 * @param {{ updateOnly?: boolean }} [opts]  when updateOnly, a measured key with
 *   no existing row is DROPPED (the matrix is curated — new langs are added by
 *   hand, not appended by a probe). Default appends new keys.
 * @returns {string[][]}          merged rows
 */
export function mergeRows(
	existing,
	header,
	measured,
	keyCol,
	ownedCols,
	opts = {},
) {
	const idx = (name) => header.indexOf(name);
	const keyIdx = idx(keyCol);
	const byKey = new Map();
	const order = [];
	for (const cells of existing) {
		const k = cells[keyIdx];
		byKey.set(k, [...cells]);
		order.push(k);
	}
	for (const m of measured) {
		const k = m[keyCol];
		let cells = byKey.get(k);
		if (!cells) {
			if (opts.updateOnly) continue; // don't append to a curated table
			cells = header.map((h) => (m[h] !== undefined ? String(m[h]) : ""));
			byKey.set(k, cells);
			order.push(k);
			continue;
		}
		for (const col of ownedCols) {
			const ci = idx(col);
			if (ci >= 0 && m[col] !== undefined) cells[ci] = String(m[col]);
		}
	}
	return order.map((k) => byKey.get(k));
}

/**
 * Merge a measured `src` token (e.g. "ci") into an existing one (e.g. "dev") so a
 * row measured on both surfaces reads "dev+ci". Order kept deterministic
 * (dev before ci). An empty/missing existing value just yields the new token.
 *
 * @param {string} existing
 * @param {string} measured
 * @returns {string}
 */
export function mergeSrc(existing, measured) {
	const set = new Set();
	for (const part of String(existing ?? "").split("+")) {
		const t = part.trim();
		if (t && t !== "—") set.add(t);
	}
	if (measured) set.add(measured.trim());
	const order = ["dev", "ci"];
	return [...set]
		.sort((a, b) => {
			const ia = order.indexOf(a);
			const ib = order.indexOf(b);
			return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
		})
		.join("+");
}

/**
 * Replace the table located by `headerMarker` in `text` with a table built from
 * `header`/`sep`/`rows`. If no such table exists, returns null (caller decides
 * whether to append a fresh table). Preserves everything outside the table.
 *
 * @returns {string | null}
 */
export function replaceTable(text, headerMarker, header, sep, rows) {
	const tbl = parseTable(text, headerMarker);
	if (!tbl) return null;
	const lines = text.split("\n");
	const rendered = [renderRow(header), sep, ...rows.map(renderRow)];
	lines.splice(tbl.start, tbl.end - tbl.start, ...rendered);
	return lines.join("\n");
}

/**
 * Merge prior rows into a NEW header shape by column NAME, tolerating a schema
 * change between the prior doc and this run (#469). Unlike `mergeRows` (which
 * requires identical headers), this reshapes each prior row that this run did
 * NOT capture onto `newHeader`: columns present in both are carried by name,
 * columns the prior row lacked (a column added this run) are filled with
 * `placeholder`, and columns dropped from the new schema are simply not
 * carried. Rows this run DID capture are the caller's fresh rows and always
 * win — pass only the prior rows NOT in `capturedKeys` as `priorRows`.
 *
 * @param {string[][]} priorRows     prior rows to reshape (already narrowed to
 *   the ones this run did not capture), in `priorHeader` column order
 * @param {string[]} priorHeader     the prior doc's header
 * @param {string[]} newHeader       this run's header (may differ in columns)
 * @param {string} keyCol            header name of the unique row key (e.g. "server")
 * @param {string | ((column: string) => string)} [placeholder]  fill value for columns the prior row lacked (a function picks it per column, #3407)
 * @returns {string[][]}             priorRows reshaped onto newHeader
 */
export function reshapeRowsByName(
	priorRows,
	priorHeader,
	newHeader,
	keyCol,
	placeholder = "·",
) {
	const priorIdx = (name) => priorHeader.indexOf(name);
	return priorRows.map((cells) =>
		newHeader.map((h) => {
			const pi = priorIdx(h);
			if (pi >= 0 && cells[pi] !== undefined) return cells[pi];
			if (h === keyCol) return cells[priorIdx(keyCol)] ?? "";
			return typeof placeholder === "function" ? placeholder(h) : placeholder;
		}),
	);
}

/**
 * Parse a `## heading` bulleted-list section (lines of the form
 * `- **<key>**: <rest>`) into an ordered Map of key → full bullet line
 * (without the leading `- `). Stops at the next `## ` heading or EOF. Returns
 * an empty Map if the section isn't found — callers treat that as "nothing to
 * carry over", never a crash.
 *
 * @param {string} text
 * @param {string} heading   e.g. "## Raw advertised capability keys"
 * @returns {Map<string, string>}
 */
export function parseBulletSection(text, heading) {
	const lines = text.split("\n");
	const map = new Map();
	let i = lines.findIndex((l) => l.trim() === heading.trim());
	if (i < 0) return map;
	i++;
	// The bold key is followed by either `:` (Raw advertised capability keys)
	// or ` (N):` (Advertised executeCommand allowlists, N = allowlist size) —
	// tolerate both so a single parser/merger works for both sections.
	const bulletRe = /^- \*\*(.+?)\*\*(?:\s*\([^)]*\))?:\s*(.*)$/;
	for (; i < lines.length; i++) {
		const line = lines[i];
		if (/^##\s/.test(line)) break;
		const m = bulletRe.exec(line);
		if (m) map.set(m[1], line.replace(/^- /, ""));
	}
	return map;
}

/**
 * Merge preserved-server bullets into a freshly-generated `## heading` section
 * of `newText`, carrying over the prior doc's bullet line for each key in
 * `keysToCarry` that has one (silently skipped if the prior doc had none for
 * that key). The merged section is re-sorted by key so preserved and freshly-
 * generated bullets interleave alphabetically, matching the generator's
 * existing sort. If `heading` isn't found in `newText`, returns `newText`
 * unchanged (fail-open — never crash the nightly over a missing section).
 *
 * @param {string} newText
 * @param {string} heading
 * @param {Map<string, string>} priorBullets   from `parseBulletSection` on the prior doc
 * @param {string[]} keysToCarry               keys (servers) to pull from `priorBullets`
 * @returns {string}
 */
export function mergeBulletSection(
	newText,
	heading,
	priorBullets,
	keysToCarry,
) {
	const lines = newText.split("\n");
	const headingIdx = lines.findIndex((l) => l.trim() === heading.trim());
	if (headingIdx < 0) return newText;
	// The section body starts after the heading, skipping a single blank line
	// (the generator always emits one), and runs up to the next `## ` heading
	// or EOF.
	const bodyStart =
		lines[headingIdx + 1] === "" ? headingIdx + 2 : headingIdx + 1;
	let bodyEnd = lines.length;
	for (let i = bodyStart; i < lines.length; i++) {
		if (/^##\s/.test(lines[i])) {
			bodyEnd = i;
			break;
		}
	}
	// The bold key is followed by either `:` (Raw advertised capability keys)
	// or ` (N):` (Advertised executeCommand allowlists, N = allowlist size) —
	// tolerate both so a single parser/merger works for both sections.
	const bulletRe = /^- \*\*(.+?)\*\*(?:\s*\([^)]*\))?:\s*(.*)$/;
	const byKey = new Map();
	// Trailing non-bullet lines within the body (e.g. a blank line at EOF when
	// this is the last section) — preserved after the sorted bullets rather than
	// dropped.
	const trailing = [];
	for (let i = bodyStart; i < bodyEnd; i++) {
		const m = bulletRe.exec(lines[i]);
		if (m) byKey.set(m[1], lines[i]);
		else trailing.push(lines[i]);
	}
	let added = false;
	for (const k of keysToCarry) {
		if (byKey.has(k)) continue; // captured this run — always wins
		const prior = priorBullets.get(k);
		if (prior === undefined) continue; // prior doc had no bullet — skip silently
		byKey.set(k, `- ${sortBulletValues(prior)}`);
		added = true;
	}
	if (!added) return newText;
	const sortedLines = [...byKey.keys()]
		.sort(compareStableStrings)
		.map((k) => byKey.get(k));
	const before = lines.slice(0, bodyStart);
	const after = lines.slice(bodyEnd);
	return [...before, ...sortedLines, ...trailing, ...after].join("\n");
}

function sortBulletValues(value) {
	const separator = value.indexOf(": ");
	if (separator < 0) return value;
	const prefix = value.slice(0, separator + 2);
	const values = value.slice(separator + 2);
	if (!values || values === "(none reported)") return value;
	return `${prefix}${sortedStrings(values.split(", ")).join(", ")}`;
}

// Deliberately a SHORT, schema-stable marker (not "| server | mode | ws-pull |")
// — the whole point of #469 is that a prior doc predating the ws-pull column
// must still be found and parsed, so the marker can't assume a column that
// might not exist yet.
const SERVER_CAPS_TABLE_MARKER = "| server | mode |";
const SERVER_CAPS_RAW_KEYS_HEADING = "## Raw advertised capability keys";
const SERVER_CAPS_EXEC_CMDS_HEADING = "## Advertised executeCommand allowlists";

/**
 * Merge a prior `docs/servercapabilities.md` into a freshly-generated one
 * (#390/#469): servers the fresh run didn't capture keep their prior table
 * row (reshaped by column NAME onto the fresh header via `reshapeRowsByName`,
 * so a schema change like the ws-pull column addition no longer disables the
 * guard — #469) and their bullet lines in both "Raw advertised capability
 * keys" and "Advertised executeCommand allowlists" (via `mergeBulletSection`,
 * which the original #390 guard didn't touch at all). Servers captured this
 * run always win — their fresh row/bullets are never overwritten by a stale
 * prior value.
 *
 * Pure (text in, text in, text out) so it's testable without spawning any LSP
 * server. Fail-open: if either doc's table is unparseable, returns the fresh
 * text unchanged (caller logs the skip; the nightly must never crash on this).
 *
 * @param {string} priorText   previous docs/servercapabilities.md content
 * @param {string} freshText   this run's freshly-generated content
 * @returns {{ text: string, preservedCount: number }}
 */
export function mergeServerCapabilitiesDoc(priorText, freshText) {
	const priorTbl = parseTable(priorText, SERVER_CAPS_TABLE_MARKER);
	const newTbl = parseTable(freshText, SERVER_CAPS_TABLE_MARKER);
	if (!priorTbl || !newTbl) {
		return { text: freshText, preservedCount: 0 };
	}
	const keyIdx = newTbl.header.indexOf("server");
	const priorKeyIdx = priorTbl.header.indexOf("server");
	if (keyIdx < 0 || priorKeyIdx < 0) {
		return { text: freshText, preservedCount: 0 };
	}
	const capturedKeys = new Set(newTbl.rows.map((c) => c[keyIdx]));
	const notCapturedPriorRows = priorTbl.rows.filter(
		(c) => !capturedKeys.has(c[priorKeyIdx]),
	);
	// #3407: a prior row carried into a column it predates is unmeasured there.
	// For the save column that is `?`, not the `·` ("declares none") every
	// boolean column uses.
	const reshaped = reshapeRowsByName(
		notCapturedPriorRows,
		priorTbl.header,
		newTbl.header,
		"server",
		(column) => (column === "save" ? "?" : "·"),
	);
	const mergedRows = [...newTbl.rows, ...reshaped].sort((a, b) =>
		compareStableStrings(a[keyIdx], b[keyIdx]),
	);
	let text = replaceTable(
		freshText,
		SERVER_CAPS_TABLE_MARKER,
		newTbl.header,
		newTbl.sep,
		mergedRows,
	);
	if (!text) {
		return { text: freshText, preservedCount: 0 };
	}
	const preservedServers = notCapturedPriorRows.map((c) => c[priorKeyIdx]);
	for (const heading of [
		SERVER_CAPS_RAW_KEYS_HEADING,
		SERVER_CAPS_EXEC_CMDS_HEADING,
	]) {
		const priorBullets = parseBulletSection(priorText, heading);
		text = mergeBulletSection(text, heading, priorBullets, preservedServers);
	}
	return { text, preservedCount: preservedServers.length };
}

// ---------------------------------------------------------------------------
// #3401: the capability-matrix staleness guards.
//
// The merge guard above preserves a row the current run did not measure, which
// is right for an ubuntu-poor host but leaves a measured cell unexpirable: the
// vue/ast-grep `first-publish=direct` cells came from the pre-#3394 attribution
// defect and NOTHING observed them afterwards, yet the guard kept them forever.
// Two bounded rules fix that, and both need a per-cell observation memory that
// outlives one nightly run:
//
//  - EXPIRY (first-publish, DATE-based): a `direct` cell whose axis the probe
//    does not re-observe is stamped once with `firstMissed` (a UTC date) and
//    degrades to `unknown` once `FIRST_PUBLISH_EXPIRY_DAYS` have elapsed. Only
//    `direct` is in the population: `empty-first` backs live
//    `emptyFirstPublish` markers, so expiring it would erase the measurement
//    behind a marker while the first-publish census stays green.
//  - HYSTERESIS (clean-behavior/tier, run-based): a change is written only after
//    `TIER_CHANGE_AGREE_RUNS` consecutive runs observe the same new value, so a
//    single flapping run (ast-grep 2 -> 2* -> 3 -> 2* across four nightlies)
//    cannot rewrite a cell. A night that measured nothing for the lang resets
//    the hold.
//
// The matrix doc is the only state the refresh persists, so the bookkeeping
// lives in a generated section of that same doc. The nightly seeds its working
// copy from the last `bot/lsp-docs-refresh` doc when that branch is ahead of
// master (scripts/seed-matrix-from-bot-branch.mjs), so the state advances per
// nightly run whether or not the bot PR has merged. Nothing here is a
// measurement; the section is bookkeeping.
// ---------------------------------------------------------------------------

/**
 * #3401: elapsed days after the first miss before a `direct` `first-publish`
 * cell degrades to `unknown`. Five days is long enough that a transient runner
 * or toolchain gap does not erase a dev-box measurement, and short enough that
 * a dead cell cannot outlive the instrument that produced it (#3310's lesson).
 * Elapsed calendar days, not runs: a skipped nightly cannot stall it.
 */
export const FIRST_PUBLISH_EXPIRY_DAYS = 5;

/**
 * #3401: consecutive agreeing runs before a `clean-behavior`/`tier` change is
 * written. Two, so one odd nightly (the ast-grep flap) is held as pending but
 * two agreeing nights commit.
 */
export const TIER_CHANGE_AGREE_RUNS = 2;

/** The one first-publish class the expiry may retire (see the block above). */
const EXPIRABLE_FIRST_PUBLISH = "direct";

/** @param {Date | number | string} now @returns {string} UTC `YYYY-MM-DD` */
function utcDay(now) {
	if (isUtcDay(now)) return now;
	return new Date(now).toISOString().slice(0, 10);
}

/** True for a real `YYYY-MM-DD` calendar date (`2026-13-45` is not). */
function isUtcDay(value) {
	if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value))
		return false;
	const ms = Date.parse(`${value}T00:00:00Z`);
	return !Number.isNaN(ms) && new Date(ms).toISOString().slice(0, 10) === value;
}

/** Whole UTC days from `from` to `to` (both `YYYY-MM-DD`); `null` if `from` is not a real date. */
function elapsedDays(from, to) {
	if (!isUtcDay(from)) return null;
	return Math.round(
		(Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) /
			86_400_000,
	);
}

const REFRESH_STATE_HEADING =
	"## Capability matrix refresh state (nightly-generated)";
const REFRESH_STATE_FENCE = "```json";
const REFRESH_STATE_FENCE_END = "```";

/**
 * Parse the `## Capability matrix refresh state` JSON block. An absent or
 * malformed block parses as `{}`: it is bookkeeping, so a lost block degrades
 * to "no memory this run", never a crash.
 *
 * @param {string} text
 * @returns {{ "first-publish"?: Record<string, { firstMissed: string }>, "clean-behavior"?: Record<string, { pendingBehavior: string, pendingTier: string, runs: number }> }}
 */
export function parseRefreshState(text) {
	const lines = String(text ?? "").split("\n");
	const headingIdx = lines.findIndex(
		(l) => l.trim() === REFRESH_STATE_HEADING.trim(),
	);
	if (headingIdx < 0) return {};
	const openIdx = lines.indexOf(REFRESH_STATE_FENCE, headingIdx + 1);
	if (openIdx < 0) return {};
	const closeIdx = lines.indexOf(REFRESH_STATE_FENCE_END, openIdx + 1);
	if (closeIdx < 0) return {};
	try {
		const parsed = JSON.parse(lines.slice(openIdx + 1, closeIdx).join("\n"));
		return parsed && typeof parsed === "object" ? parsed : {};
	} catch {
		return {};
	}
}

/**
 * Render the refresh-state section's lines, or `[]` when there is nothing to
 * remember. Keys are sorted and zero counters are dropped so a settled run
 * writes a byte-identical block and the refresh PR does not open on churn.
 */
function renderRefreshStateSection(state) {
	const firstPublish = {};
	for (const lang of Object.keys(state?.["first-publish"] ?? {}).sort(
		compareStableStrings,
	)) {
		const firstMissed = state["first-publish"][lang]?.firstMissed;
		if (isUtcDay(firstMissed)) firstPublish[lang] = { firstMissed };
	}
	const cleanBehavior = {};
	for (const lang of Object.keys(state?.["clean-behavior"] ?? {}).sort(
		compareStableStrings,
	)) {
		const pending = state["clean-behavior"][lang];
		if (pending?.pendingBehavior && pending?.pendingTier) {
			cleanBehavior[lang] = {
				pendingBehavior: pending.pendingBehavior,
				pendingTier: pending.pendingTier,
				runs: Number(pending.runs ?? 1),
			};
		}
	}
	const payload = {};
	if (Object.keys(cleanBehavior).length)
		payload["clean-behavior"] = cleanBehavior;
	if (Object.keys(firstPublish).length) payload["first-publish"] = firstPublish;
	if (Object.keys(payload).length === 0) return [];
	return [
		REFRESH_STATE_HEADING,
		"",
		"Bookkeeping for the date-based `direct` `first-publish` expiry (#3401) and",
		"the two-run `clean-behavior` hysteresis. Regenerated every run; never a",
		"measurement.",
		"",
		REFRESH_STATE_FENCE,
		JSON.stringify(payload),
		REFRESH_STATE_FENCE_END,
	];
}

/**
 * Replace (or append) the refresh-state section at the end of `text`. Placing it
 * after the generated drift footnote keeps the drift writer's own "up to the
 * next `## ` heading" scan from swallowing it.
 */
function replaceRefreshStateSection(text, section) {
	const lines = String(text).split("\n");
	const headingIdx = lines.findIndex(
		(l) => l.trim() === REFRESH_STATE_HEADING.trim(),
	);
	let kept = lines;
	if (headingIdx >= 0) {
		let end = lines.length;
		for (let i = headingIdx + 1; i < lines.length; i++) {
			if (/^##\s/.test(lines[i])) {
				end = i;
				break;
			}
		}
		kept = [...lines.slice(0, headingIdx), ...lines.slice(end)];
	}
	while (kept.length && kept.at(-1) === "") kept.pop();
	const body = kept.join("\n");
	if (section.length === 0) return `${body}\n`;
	return `${body}\n\n${section.join("\n")}\n`;
}

/**
 * Refresh docs/lsp-capability-matrix.md from one probe run, applying the two
 * #3401 staleness guards. Text in, text out (plus counts) so the nightly's real
 * refresh entry is testable with recorded run inputs and no LSP spawn.
 *
 * @param {string} text  the current doc
 * @param {Array<{ lang: string, firstPublish?: string | null, cleanBehavior?: string | null, tier?: string | null }>} observations
 *   this run's comparable observations, already resolved onto target langs by
 *   the caller (a non-comparable axis is `null`)
 * @param {{ src?: string, marker?: string, agreeRuns?: number, expireDays?: number, now?: Date | number | string, probedLangs?: Iterable<string> }} [opts]
 *   `now` is the injected clock (default: the real one); `probedLangs` scopes a
 *   subset probe: a lang outside it keeps its bookkeeping untouched. Omitted
 *   means a full run.
 * @returns {{ text: string, changed: boolean, reason?: string, expired: number, pending: number, committed: number, expiredLangs: string[], pendingLangs: string[], committedLangs: string[] }}
 */
export function refreshCapabilityMatrix(text, observations, opts = {}) {
	const marker = opts.marker ?? "| lang | server |";
	const src = opts.src ?? "ci";
	const agreeRuns = Math.max(
		1,
		Number(opts.agreeRuns ?? TIER_CHANGE_AGREE_RUNS),
	);
	const expireDays = Math.max(
		1,
		Number(opts.expireDays ?? FIRST_PUBLISH_EXPIRY_DAYS),
	);
	const today = utcDay(opts.now ?? new Date());
	const probed = opts.probedLangs ? new Set(opts.probedLangs) : null;
	const tbl = parseTable(text, marker);
	if (!tbl) {
		return {
			text,
			changed: false,
			reason: "capability table not found in doc",
			expired: 0,
			pending: 0,
			committed: 0,
			expiredLangs: [],
			pendingLangs: [],
			committedLangs: [],
		};
	}
	const idx = (name) => tbl.header.indexOf(name);
	const langIdx = idx("lang");
	const srcIdx = idx("src");
	const fpIdx = idx("first-publish");
	const cbIdx = idx("clean-behavior");
	const tierIdx = idx("tier");
	const byLang = new Map((observations ?? []).map((o) => [o.lang, o]));
	const prior = parseRefreshState(text);
	const priorFp = prior["first-publish"] ?? {};
	const priorCb = prior["clean-behavior"] ?? {};
	const nextState = { "first-publish": {}, "clean-behavior": {} };
	const expiredLangs = [];
	const pendingLangs = [];
	const committedLangs = [];
	const measured = [];
	for (const cells of tbl.rows) {
		const lang = cells[langIdx];
		const observed = byLang.get(lang);
		const cell = { lang };
		if (probed && !probed.has(lang)) {
			// A subset probe says nothing about this lang: neither advance nor drop
			// its bookkeeping (a one-lang dev run must not tick or expire cells).
			if (priorFp[lang]) nextState["first-publish"][lang] = priorFp[lang];
			if (priorCb[lang]) nextState["clean-behavior"][lang] = priorCb[lang];
			measured.push(cell);
			continue;
		}
		if (observed)
			cell.src = mergeSrc(srcIdx >= 0 ? (cells[srcIdx] ?? "") : "", src);
		// first-publish: an observation writes immediately; a `direct` cell the
		// probe no longer observes is stamped with its first miss and, once
		// `expireDays` have elapsed, expired.
		const observedFp = observed?.firstPublish ?? null;
		const currentFp = fpIdx >= 0 ? cells[fpIdx] : "";
		if (observedFp) {
			cell["first-publish"] = observedFp;
		} else if (currentFp === EXPIRABLE_FIRST_PUBLISH) {
			// A missing, garbage or future stamp restarts the clock today.
			const elapsed = elapsedDays(priorFp[lang]?.firstMissed, today);
			if (elapsed !== null && elapsed >= 0) {
				if (elapsed >= expireDays) {
					cell["first-publish"] = "unknown";
					expiredLangs.push(lang);
				} else {
					nextState["first-publish"][lang] = priorFp[lang];
				}
			} else {
				nextState["first-publish"][lang] = { firstMissed: today };
			}
		}
		// clean-behavior/tier: hold a change until `agreeRuns` runs agree.
		const observedCb = observed?.cleanBehavior ?? null;
		if (observedCb) {
			const observedTier = observed.tier ?? "";
			const currentCb = cbIdx >= 0 ? cells[cbIdx] : "";
			const currentTier = tierIdx >= 0 ? cells[tierIdx] : "";
			if (observedCb !== currentCb || observedTier !== currentTier) {
				const held = priorCb[lang];
				const sameHeld =
					held?.pendingBehavior === observedCb &&
					held?.pendingTier === observedTier;
				const runs = sameHeld ? Number(held.runs ?? 1) + 1 : 1;
				if (sameHeld && runs >= agreeRuns) {
					cell["clean-behavior"] = observedCb;
					cell.tier = observedTier;
					committedLangs.push(lang);
				} else {
					nextState["clean-behavior"][lang] = {
						pendingBehavior: observedCb,
						pendingTier: observedTier,
						runs,
					};
					pendingLangs.push(lang);
				}
			}
		}
		measured.push(cell);
	}
	const merged = mergeRows(tbl.rows, tbl.header, measured, "lang", [
		"clean-behavior",
		"first-publish",
		"tier",
		"src",
	]);
	// `replaceTable` only returns null for a table `parseTable` cannot find, and
	// this same text and marker were parsed above.
	const out = replaceRefreshStateSection(
		replaceTable(text, marker, tbl.header, tbl.sep, merged),
		renderRefreshStateSection(nextState),
	);
	return {
		text: out,
		changed: out !== text,
		expired: expiredLangs.length,
		pending: pendingLangs.length,
		committed: committedLangs.length,
		expiredLangs,
		pendingLangs,
		committedLangs,
	};
}
